select * from AspNetUsers
select * from UserProfiles
select * from AssessmentQuestions
select * from AssessmentAnswers
select * from AssessmentAttempts
select * from AssessmentResults
SELECT COUNT(*) FROM AssessmentQuestions
select * from careercomparisons
SELECT COUNT(*) FROM Careers;
select * from Journey1Results
select * from Journey2Results
select * from Journey1Questions
SELECT COUNT(*) FROM Journey1Questions;